apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-svc
spec:
  type: NodePort
  selector:
    app: fastapi-for-students-pod
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
