# Имя для данного workflow
name: Test code and deploy
# Триггер по которому будет срабатывать workflow, в данном случае при отправке кода в ветку master
on:
  push:
     branches: [master]
# Перечисление списка задач в данном workflow
jobs:
  test:
    # Название задачи
    name: Test code
    # Тип ВМ, на которой будет запущена задача
    runs-on: ubuntu-latest
    # Шаги выполняемые в рамках задачиhttps://imgur.com/3gYIfqf
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        env:
          DATABASE_URL: sqlite:///./sqlite.db
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host yandex_server
            HostName ${{ secrets.HOST }}
            User ${{ secrets.LOGIN }}
            Port ${{ secrets.PORT }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Rsync files to server
        run: rsync -rav --delete * yandex_server:~/

      - name: Run command
        run: ssh yandex_server 'sudo docker-compose up'
